str_var = "Hello World"
int_var = 1
float_var = 12.345
complex_var = 2 + 3j
list_var = ["apple", "banana", "cherry"]
tuple_var = ("apple", "banana", "cherry")
range_var = range(1, 11)
dict_var = {"id": "1", "name": "Murad"}
set_var = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
frozen_var = frozenset({1, 2, 3, 4, 5, 6, 7, 8, 9, 10})
boolean_var = True
bytes_var = b"Hello"
bytearray_var = bytearray(b"Hello")
memoryview_var = memoryview(bytes_var)
nonetype_var = None
